services:
  db:
    image: mysql:8.0
    container_name: iud_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projects_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: iud_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  migrate:
    build: ./back
    container_name: iud_migrate
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env
    depends_on:
      db:
        condition: service_healthy
    command: ["alembic", "upgrade", "head"]

  backend:
    build: ./back
    container_name: iud_api
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully

volumes:
  mysql_data:
  redis_data:
